// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngqwdmlbawkobqhbrfsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ncXdkbWxiYXdrb2JxaGJyZnNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODY1ODUsImV4cCI6MjA3MDU2MjU4NX0.JrQrYWtzeyhhtN7grqC6rfYI_slFykTJHyXfBE65A9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});